### ISSUE TITLE
Support for 3.0.0

### ISSUE THREAD

**Issue by pekkah** [martincostello/xunit-logging#75] opened 2019-10-21 08:08 UTC
**Is your feature request related to a problem? Please describe.**
Current version does not work with 3.0.0 version of the logging. 

Throws 
```
System.TypeLoadException : Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state)
```
NullScope has been removed.

**Comment by martincostello** [comment] 2019-10-21 12:41
@pekkah Are you sure this isn't an issue from within your own application code?

I can't any references to `NullScope` in the codebase here, and the tests have already been updated to target `netcoreapp3.0` and have a test that enables scopes, so I'm not sure how the issue would manifest from the library alone.

Can you share a test that reproduces this issue?

**Comment by martincostello** [comment] 2019-10-31 13:22
Closing as unable to reproduce in any applications using ASP.NET Core 3.0.0.

**Closed by martincostello** 2019-10-31 13:22 UTC
Labels: help wanted, question
